import Head from 'next/head'
import Main from '../components/Main'
import { Inter } from 'next/font/google'
import About from '../components/About'
import Lines from '../components/Lines'
import Contact from '../components/Contact'
import Catalogo from '../components/Catalogo'
import Map from '../components/Map'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>¡Nosotros lo tenemos!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Main/>
      <About/>
      <Lines/>
      <Catalogo/>
      <Contact/>
      <Map/>
    </div>
  )
}
